[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true
